export const BILL_SAVE_REQUEST = 'BILL_SAVE_REQUEST'
export const BILL_SAVE_SUCCESS = 'BILL_SAVE_SUCCESS'
export const BILL_SAVE_FINISHED = 'BILL_SAVE_FINISHED'
export const BILL_SAVE_ERROR = 'BILL_SAVE_ERROR'

export const BILLS_FETCH_REQUEST = 'BILLS_FETCH_REQUEST'
export const BILLS_FETCH_SUCCESS = 'BILLS_FETCH_SUCCESS'
export const BILLS_FETCH_EMPTY = 'BILLS_FETCH_SUCCESS'
export const BILLS_FETCH_ERROR = 'BILLS_FETCH_ERROR'

export const FETCH_A_BILL_REQUEST = 'FETCH_A_BILL_REQUEST'
export const FETCH_A_BILL_SUCCESS = 'FETCH_A_BILL_SUCCESS'
export const FETCH_A_BILL_FAILURE = 'FETCH_A_BILL_FAILURE'

export const CLIENT_BILLS_FETCH_REQUEST = 'CLIENT_BILLS_FETCH_REQUEST'
export const CLIENT_BILLS_FETCH_SUCCESS = 'CLIENT_BILLS_FETCH_SUCCESS'
export const CLIENT_BILLS_EMPTY = 'CLIENTS_BILLS_EMPTY'
export const CLIENT_BILLS_FETCH_ERROR = 'CLIENT_BILLS_FETCH_ERROR'

export const USER_BILLS_FETCH_REQUEST = 'USER_BILLS_FETCH_REQUEST'
export const USER_BILLS_FETCH_SUCCESS = 'USER_BILLS_FETCH_SUCCESS'
export const USER_BILLS_EMPTY = 'USER_BILLS_EMPTY'
export const USER_BILLS_FETCH_ERROR = 'USER_BILLS_FETCH_ERROR'

export const BILL_UPDATE_REQUEST = 'BILL_UPDATE_REQUEST'
export const BILL_UPDATE_SUCCESS = 'BILL_UPDATE_SUCCESS'
export const BILL_UPDATE_FINISHED = 'BILL_UPDATE_FINISHED'
export const BILL_UPDATE_ERROR = 'BILL_UPDATE_ERROR'

export const DELETE_A_BILL_REQUEST = 'DELETE_A_BILL_REQUEST'
export const DELETE_A_BILL_SUCCESS = 'DELETE_A_BILL_SUCCESS'
export const DELETE_A_BILL_FINISHED = 'DELETE_A_BILL_FINISHED'
export const DELETE_A_BILL_FAILURE = 'DELETE_A_BILL_FAILURE'