export const BILL_SAVE_REQUEST = 'BILL_SAVE_REQUEST'
export const BILL_SAVE_SUCCESS = 'BILL_SAVE_SUCCESS'
export const BILL_SAVE_ERROR = 'BILL_SAVE_ERROR'

export const BILLS_FETCH_REQUEST = 'BILLS_FETCH_RREQUEST'
export const BILLS_FETCH_SUCCESS = 'BILLS_FETCH_SUCCESS'
export const BILLS_FETCH_ERROR = 'BILLS_FETCH_ERROR'