export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FINISHED = 'CREATE_CLIENT_FINISHED'
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE'

export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST'
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS'
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE'

export const FETCH_SINGLE_CLIENT_REQUEST = 'FETCH_SINGLE_CLIENT_REQUEST'
export const FETCH_SINGLE_CLIENT_SUCCESS = 'FETCH_SINGLE_CLIENT_SUCCESS'
export const FETCH_SINGLE_CLIENT_FAILURE = 'FETCH_SINGLE_CLIENT_FAILURE'

export const DELETE_SINGLE_CLIENT_REQUEST = 'DELETE_SINGLE_CLIENT_REQUEST'
export const DELETE_SINGLE_CLIENT_SUCCESS = 'DELETE_SINGLE_CLIENT_SUCCESS'
export const DELETE_SINGLE_CLIENT_FAILURE = 'DELETE_SINGLE_CLIENT_FAILURE'

export const UPDATE_SINGLE_CLIENT_REQUEST = 'UPDATE_SINGLE_CLIENT_REQUEST'
export const UPDATE_SINGLE_CLIENT_SUCCESS = 'UPDATE_SINGLE_CLIENT_SUCCESS'
export const UPDATE_SINGLE_CLIENT_FAILURE = 'UPDATE_SINGLE_CLIENT_FAILURE'
