export const COMPANY_SAVE_REQUEST = 'COMPANY_SAVE_REQUEST'
export const COMPANY_SAVE_SUCCESS = 'COMPANY_SAVE_SUCCESS'
export const COMPANY_SAVE_FINISHED = 'COMPANY_SAVE_FINISHED'
export const COMPANY_SAVE_ERROR = 'COMPANY_SAVE_ERROR'

export const COMPANIES_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST'
export const COMPANIES_FETCH_SUCCESS = 'COMPANY_FETCH_SUCCESS'
export const COMPANIES_FETCH_EMPTY = 'COMPANY_FETCH_EMPTY'
export const COMPANIES_FETCH_ERROR = 'COMPANY_FETCH_ERROR'

export const FETCH_A_COMPANY_REQUEST = 'FETCH_A_COMPANY_REQUEST'
export const FETCH_A_COMPANY_SUCCESS = 'FETCH_A_COMPANY_SUCCESS'
export const FETCH_A_COMPANY_FAILURE = 'FETCH_A_COMPANY_FAILURE'

export const CLIENT_COMPANIES_FETCH_REQUEST = 'CLIENT_COMPANY_FETCH_REQUEST'
export const CLIENT_COMPANIES_FETCH_SUCCESS = 'CLIENT_COMPANY_FETCH_SUCCESS'
export const CLIENT_COMPANIES_EMPTY = 'CLIENT_COMPANY_EMPTY'
export const CLIENT_COMPANIES_FETCH_ERROR = 'CLIENT_COMPANY_FETCH_ERROR'

export const USER_COMPANIES_FETCH_REQUEST = 'USER_COMPANIES_FETCH_REQUEST'
export const USER_COMPANIES_FETCH_SUCCESS = 'USER_COMPANIES_FETCH_SUCCESS'
export const USER_COMPANIES_EMPTY = 'USER_COMPANIES_EMPTY'
export const USER_COMPANIES_FETCH_ERROR = 'USER_COMPANIES_FETCH_ERROR'

export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST'
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS'
export const COMPANY_UPDATE_FINISHED = 'COMPANY_UPDATE_FINISHED'
export const COMPANY_UPDATE_ERROR = 'COMPANY_UPDATE_ERROR'

export const DELETE_A_COMPANY_REQUEST = 'DELETE_A_COMPANY_REQUEST'
export const DELETE_A_COMPANY_SUCCESS = 'DELETE_A_COMPANY_SUCCESS'
export const DELETE_A_COMPANY_FINISHED = 'DELETE_A_COMPANY_FINISHED'
export const DELETE_A_COMPANY_FAILURE = 'DELETE_A_COMPANY_FAILURE'