export const CRIMINAL_SAVE_REQUEST = 'CRIMINAL_SAVE_REQUEST'
export const CRIMINAL_SAVE_SUCCESS = 'CRIMINAL_SAVE_SUCCESS'
export const CRIMINAL_SAVE_FINISHED = 'CRIMINAL_SAVE_FINISHED'
export const CRIMINAL_SAVE_ERROR = 'CRIMINAL_SAVE_ERROR'

export const CRIMINAL_FETCH_REQUEST = 'CRIMINAL_FETCH_REQUEST'
export const CRIMINAL_FETCH_SUCCESS = 'CRIMINAL_FETCH_SUCCESS'
export const CRIMINAL_FETCH_ERROR = 'CRIMINAL_FETCH_ERROR'

export const FETCH_A_CRIMINAL_REQUEST = 'FETCH_A_CRIMINAL_REQUEST'
export const FETCH_A_CRIMINAL_SUCCESS = 'FETCH_A_CRIMINAL_SUCCESS'
export const FETCH_A_CRIMINAL_FAILURE = 'FETCH_A_CRIMINAL_FAILURE'

export const CLIENT_CRIMINAL_FETCH_REQUEST = 'CLIENT_CRIMINAL_FETCH_REQUEST'
export const CLIENT_CRIMINAL_FETCH_SUCCESS = 'CLIENT_CRIMINAL_FETCH_SUCCESS'
export const CLIENT_CRIMINAL_FETCH_ERROR = 'CLIENT_CRIMINAL_FETCH_ERROR'

export const USER_CRIMINAL_FETCH_REQUEST = 'USER_CRIMINAL_FETCH_REQUEST'
export const USER_CRIMINAL_FETCH_SUCCESS = 'USER_CRIMINAL_FETCH_SUCCESS'
export const USER_CRIMINAL_FETCH_ERROR = 'USER_CRIMINAL_FETCH_ERROR'

export const CRIMINAL_UPDATE_REQUEST = 'CRIMINAL_UPDATE_REQUEST'
export const CRIMINAL_UPDATE_SUCCESS = 'CRIMINAL_UPDATE_SUCCESS'
export const CRIMINAL_UPDATE_FINISHED = 'CRIMINAL_UPDATE_FINISHED'
export const CRIMINAL_UPDATE_ERROR = 'CRIMINAL_UPDATE_ERROR'

export const DELETE_A_CRIMINAL_REQUEST = 'DELETE_A_CRIMINAL_REQUEST'
export const DELETE_A_CRIMINAL_SUCCESS = 'DELETE_A_CRIMINAL_SUCCESS'
export const DELETE_A_CRIMINAL_FINISHED = 'DELETE_A_CRIMINAL_FINISHED'
export const DELETE_A_CRIMINAL_FAILURE = 'DELETE_A_CRIMINAL_FAILURE'