export const SAVE_NOTE_REQUEST = 'SAVE_NOTE_REQUEST'
export const SAVE_NOTE_SUCCESS = 'SAVE_NOTE_SUCCESS'
export const SAVE_NOTE_FINISHED = 'SAVE_NOTE_FINISHED'
export const SAVE_NOTE_FAILURE = 'SAVE_NOTE_FAILURE'

export const FETCH_ALL_USER_NOTES_REQUEST = 'FETCH_ALL_USER_NOTES_REQUEST'
export const FETCH_ALL_USER_NOTES_SUCCESS = 'FETCH_ALL_USER_NOTES_SUCCESS'
export const USER_NOTES_EMPTY = 'USER_NOTES_EMPTY'
export const FETCH_ALL_USER_NOTES_FAILURE = 'FETCH_ALL_USER_NOTES_FAILURE'

export const FETCH_A_NOTE_REQUEST = 'FETCH_A_NOTE_REQUEST'
export const FETCH_A_NOTE_SUCCESS = 'FETCH_A_NOTE_SUCCESS'
export const FETCH_A_NOTE_FAILURE = 'FETCH_A_NOTE_FAILURE'

export const DELETE_A_NOTE_REQUEST = 'DELETE_A_NOTE_REQUEST'
export const DELETE_A_NOTE_SUCCESS = 'DELETE_A_NOTE_SUCCESS'
export const DELETE_A_NOTE_FINISHED = 'DELETE_A_NOTE_FINISHED'
export const DELETE_A_NOTE_FAILURE = 'DELETE_A_NOTE_FAILURE'